SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libExec libProfData\
             libUtils  \
			 libIOInterface 
EXECUTABLE=dumptree
MODE=CPP
CPP_TAGS_FILE=profiler-binaries-dumptTree-c++.tags



include ../../makefile.include
