LINKED_LIBS= libProfData\
             libUtils  \
			 libIOInterface \
			 libTest

BUILD_TIME_TESTS=load path callCount stack
CPP_TAGS_FILE=profiler-tests-c++.tags
MODE=CPP

USE_BOOST=YES

NO_INTEL=YES

include ../makefile.include
