LINKED_LIBS= libSource libExec libCallgrindData libProfData \
             libUtils  \
			 libString \
			 libIOInterface \
			 libTest
MAKE_DIRS=gcgvApp

BUILD_TIME_TESTS=stack config source load path callCount graph 
CPP_TAGS_FILE=profiler-tests-c++.tags
MODE=CPP

USE_BOOST=YES
BOOST_MODULES+=regex

NO_INTEL=YES

include ../makefile.include
