SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libExec libCallgrindData libProfData\
             libUtils  \
			 libIOInterface 
EXECUTABLE=profile
MODE=CPP
CPP_TAGS_FILE=profiler-profile-c++.tags



include ../../makefile.include
