SOURCES=$(shell echo *.cpp)

LINKED_LIBS= libExec libCallgrindData libProfData libSource\
             libScreen \
             libUtils  \
             libString  \
			 libIOInterface 
EXECUTABLE=profile
MODE=CPP
CPP_TAGS_FILE=profiler-profile-c++.tags
EXTERNAL_LIBS=-lncurses



include ../../makefile.include
