EXPORT_INCLUDES=$(shell echo *.h *.hpp)
SOURCES=$(shell echo *.cpp)

ADDITIONAL_INCLUDE_FLAGS=../libExec/

MODE=CPP
TARGET_LIB=libProfData
TAGS_FILE=profiler-libdata-c++.tags

LINKED_LIBS=libSource libString libIOInterface libUtils 

include ../makefile.include
