EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TARGET_LIB=libSource
TAGS_FILE=profiler-libsource-c++.tags

ADDITIONAL_INCLUDE_FLAGS=../libExec/

LINKED_LIBS=libIOInterface libString libUtils libProfData

include ../makefile.include
