EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TARGET_LIB=libSource
TAGS_FILE=profiler-libsource-c++.tags

LINKED_LIBS=libIOInterface libUtils libProfData

include ../makefile.include
