EXPORT_INCLUDES=$(shell echo *.h)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TARGET_LIB=libExec
TAGS_FILE=profiler-libexec-c++.tags

LINKED_LIBS=libSource libProfData libIOInterface libUtils

include ../makefile.include
