EXPORT_INCLUDES=$(shell echo *.h *.hpp)
SOURCES=$(shell echo *.cpp)

MODE=CPP
TARGET_LIB=libProfData
TAGS_FILE=profiler-libdata-c++.tags

LINKED_LIBS=libIOInterface libUtils

include ../makefile.include
