LINKED_LIBS= libSource libExec libCallgrindData libProfData\
             libUtils  \
			 libString \
			 libIOInterface \
			 libTest

BUILD_TIME_TESTS=app 
MODE=CPP

USE_BOOST=YES

NO_INTEL=YES

include ../../makefile.include
