LINKED_LIBS= libSource libExec libCommands libMeta libScreen libCallgrindData libProfData\
             libUtils  \
			 libString \
			 libIOInterface \
			 libTest

EXTERNAL_LIBS=-lncurses
BUILD_TIME_TESTS=app 
MODE=CPP

USE_BOOST=YES

NO_INTEL=YES

include ../../makefile.include
